version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3456:8080"
      - "5454:80"
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: node server.js
  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "3000:9000"
    networks:
      - app-network
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - app-network
    command: redis-server --requirepass bigbananas
      
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
